name 'test-repo'
maintainer 'Sander Bel'
maintainer_email 'sander@proapps.be'
description 'Test!'
long_description 'A long test'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/belsander'
source_url 'https://github.com/belsander'
supports 'ubuntu'
